### ISSUE TITLE
multi-stage transfer learning strategy

### ISSUE THREAD

**Issue by szw811** [yongsongH/Infrared_Image_SR_PSRGAN#1]
May I ask which part of the code reflects the multi-stage transfer learning strategy

**Comment by yongsongH** [comment]
Hello, thank you for your attention.
The code for the transfer learning strategy will be reviewed as we are considering applying for a software copyright. 
I regret that there is no plan to release at this moment.
However, I will provide the training details.
I sincerely hope this will help you in your work.
***
The key problem is to **fix the parameters' weights**, as mentioned in the paper.

1. The **PSGAN** is trained using the **IR100 dataset**, and then the **main path module** parameters are fixed.
2. Next, we retrain the parameters for the **branch module** using the **DIV2K dataset**. Please be careful, the main path module's parameters will not be updated at this time. In this stage, we fix the parameters in the branch module.
3. Finally, we train the whole network again using the infrared image dataset. However, only the parameters in the tail module are updated.

For more information about the dataset, please check my [homepage](https://hyongsong.work).
For fixed-parameter code, please refer to the official PyTorch documents.

**Comment by szw811** [comment]
> Hello, thank you for your attention. The code for the transfer learning strategy will be reviewed as we are considering applying for a software copyright. I regret that there is no plan to release at this moment. However, I will provide the training details. I sincerely hope this will help you in your work.
> 
> The key problem is to **fix the parameters' weights**, as mentioned in the paper.
> 
> 1. The **PSGAN** is trained using the **IR100 dataset**, and then the **main path module** parameters are fixed.
> 2. Next, we retrain the parameters for the **branch module** using the **DIV2K dataset**. Please be careful, the main path module's parameters will not be updated at this time. In this stage, we fix the parameters in the branch module.
> 3. Finally, we train the whole network again using the infrared image dataset. However, only the parameters in the tail module are updated.
> 
> For more information about the dataset, please check my [homepage](https://hyongsong.work). For fixed-parameter code, please refer to the official PyTorch documents.

Hello! Thank you very much for your reply which helped me a lot!

By the way,  may I ask three more questions?
First,  **Is the tail module a component of main path module**? So are the tail module's parameters  also not be updated at stage2?
Second, **whether the branch module is SLRDB, namely the KD module in the code**？
Third, **are these trainings performed in the same epoch**? Or maybe, for example, 1000 epochs for stage1, 1000 epochs for stage2 and 1000 epochs for stage3.

**Thanks again for your reply!**

**Comment by yongsongH** [comment]
Hi 👋
I will briefly address your concerns.

- Yes. The parameters in the model are updated when changing the training dataset, except the modules with fixed parameters.
- Yes, as you mentioned.
- In this work, there is no limit on the number of training epochs. However, because GAN-based models have the risk of model collapse, I discourage a lot of training sessions. According to my experiments, the earlier experiments showed better results.

Cheers

**Comment by szw811** [comment]
Thank you very much for your reply!!!
