### ISSUE TITLE
What is "latest model/20000_G.pth"? 

### ISSUE THREAD

**Issue by ProBURN-E** [yongsongH/Infrared_Image_SR_PSRGAN#10]
![image](https://github.com/yongsongH/Infrared_Image_SR_PSRGAN/assets/71887679/0e9460b7-ecc0-46b0-980e-168913cc571d)
Thanks for your great work!
As shown in the picture, in main_train_kdsrgan.py line 123, I wonder what is "latest model/20000_G.pth"? How to get this weights?

**Comment by yongsongH** [comment]
Hello!

Thank you for your attention to our work.
As you mentioned, some pre-trained models were loaded.
We tried different batch sizes like 32 and 64 and then tried loading those models.

I would recommend that you can try ablation experiments in different configurations and then load these models, some cases are beneficial.
Hope this reply addresses your concerns.

**Comment by ProBURN-E** [comment]
Thank you for your reply! It helps me a lot.
I also want to ask, is the pre-trained model loaded here the training result obtained through a complete multi-stage training strategy (as in main_train_kdsrgan.py)? If so, how to train from scratch?

**Comment by yongsongH** [comment]
The multi-stage training happens after the pre-trained model is loaded. Perhaps you could try different settings according to your needs.
