### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by liu1216** [yongsongH/Infrared_Image_SR_PSRGAN#2]
Sorry to disturb you, but thank you for your contribution to infrared image super-resolution. Is the 100 images used in cvc09 for training mentioned in your paper randomly selected by day and night? Can you also share result-a and result-c，thank you.

**Comment by yongsongH** [comment]
Thank you for your attention. 👋
The test dataset as shown in this 🔗 https://figshare.com/articles/dataset/PSRGAN/13359632
For more details, please check my homepage.
https://hyongsong.work/

**Comment by liu1216** [comment]
Thank you for your reply, which is very helpful to me.

**Comment by panlanlan** [comment]
Sorry to trouble you ,the modle of this SR where I can get ,I can not open this link

**Comment by yongsongH** [comment]
> Sorry to trouble you ,the modle of this SR where I can get ,I can not open this link

Pre-trained models can be downloaded from this [site](https://figshare.com/articles/dataset/Pre-trained_models/16591973).
