### ISSUE TITLE
How can I scaling double original image?

### ISSUE THREAD

**Issue by godhj93** [yongsongH/Infrared_Image_SR_PSRGAN#3]
Hi, It is very impressive research to enhance resolution for IR image.

I want to scale up low resolution infrared images using your network, but when I set value "sf=2" then the output image is black.
(sf=4 works well.)

Do you have any idea? thanks.

**Comment by yongsongH** [comment]
Thank you for your kind words.😄
For your question, I think 🤔 maybe you could get the new pre-trained model (5000_G) and try again.

The model can be found in this link:
https://figshare.com/articles/dataset/Pre-trained_models/16591973
Of course, I think it is important to update the setting file.
https://github.com/yongsongH/Infrared_Image_SR_PSRGAN/blob/master/results/results-A_75000_G/results-A_75000_G.log
Using the new parameters.

**Comment by godhj93** [comment]
Cool! Thanks!
