### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by Rheazheng** [yongsongH/Infrared_Image_SR_PSRGAN#4]
Thanks for your contribution in Infrared Image super-resolution. I have a question about IR100 dataset. 
There are 100 images in this dataset.  Do I need to expand on this dataset by partitioning them patches? Because I saw your dataset folder directory "IR100_sub_1500/HR" in your option file "train_kdsrgan.json". If necessary,how to partion them? eg, patch_size, number of patches.

**Comment by yongsongH** [comment]
Hi, there 👋

Thank you for your attention to our work.
I think your question is about the data argument.
It has been included in the training code.
Please feel free to use the code.

If this work is helpful, welcome to cite it!
Thanks a lot! 🎉

**Comment by Rheazheng** [comment]
> Hi, there 👋
> 
> Thank you for your attention to our work. I think your question is about the data argument. It has been included in the training code. Please feel free to use the code.
> 
> If this work is helpful, welcome to cite it! Thanks a lot! 🎉

Sorry,I think I probably didn't express clear. I just want to know,how many images in your 'dataroot_H' folder "IR100_sub_1500/HR" ? only 100 images?

**Comment by yongsongH** [comment]
Yes.
I have been trying to use the 1500 sub-image generated from the IR100 to train the model. 
But, I make the code can generate the sub-image.
In that case, you only need to use the IR100 with 100 images.
