### ISSUE TITLE
How can I train the network

### ISSUE THREAD

**Issue by Einkazusa** [yongsongH/Infrared_Image_SR_PSRGAN#5]
Thanks for your work on ir images~ When I tray to run ''main_train_kdsrgan.py", I find that there's no such file: 'latest model/20000_G.pth'. Is this the file trained on the visable image dataset? And how can I get this file
I'm really looking for your help o(╥﹏╥)o

**Comment by yongsongH** [comment]
Hi, thank you for your attention to our work!

The pre-trained model is released, I recommend testing the datasets directly.
The links you can find on the pages.
