### ISSUE TITLE
Discriminator model 

### ISSUE THREAD

**Issue by alpcangulpinar** [yongsongH/Infrared_Image_SR_PSRGAN#6]
hello. I want to train the network with my own dataset. Do I need the D_prtrained model? I dont understand clearlu cause i am new in this topic.

**Comment by yongsongH** [comment]
Thank you for your attention to our work!

I think it might be faster to converge the model if you use a pre-trained model.
But considering that you need to train on a different dataset, maybe domain shift is possible.
Perhaps trying both would be a better option.

By the way, please consider citing this work if it's helpful to you, it's very beneficial for us! Thanks!
