### ISSUE TITLE
multi-stage transfer learning strategy

### ISSUE THREAD

**Issue by tianjiaowan** [yongsongH/Infrared_Image_SR_PSRGAN#7]
Hello Dr. Huang, how can we adjust the parameters in your code to achieve the multi-stage transfer learning strategy, I hope you can explain how to run it to achieve this strategy?

**Comment by yongsongH** [comment]
Hi, there!

Thank you for your attention to our work.
The details about the training strategy for this work can be found in this link:
https://github.com/yongsongH/Infrared_Image_SR_PSRGAN/issues/1

I have replied to this issue before, hope this helps you.
