### ISSUE TITLE
Resolution amplification

### ISSUE THREAD

**Issue by cttiiiiiii** [yongsongH/Infrared_Image_SR_PSRGAN#9]
Hello! I ran into a problem. After running the test file, I found that my image did not achieve resolution enlargement. Is there something wrong with my step? Where can I adjust the degree of resolution enlargement? I am new to this field and would really appreciate your help, thank you!

**Comment by yongsongH** [comment]
Thank you for your attention to our work @cttiiiiiii.

I recommend that you maybe can check the details of this [log](https://github.com/yongsongH/Infrared_Image_SR_PSRGAN/blob/master/results/results-A_75000_G/results-A_75000_G.log) and run it again after making sure that the settings are all the same.
